kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: load-test
spec:
  args:
    - name: linkerd-enabled
      value: enabled
  metrics:
    - name: pass
      interval: 30s
      successCondition: result[0] >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.linkerd-viz.svc.cluster.local:9090
          query: |
            sum(irate(response_total{classification="success", namespace="default", direction="inbound", app="example-argocd-canary-linkerd"}[30s])) by (deployment) / sum(irate(response_total{namespace="default", direction="inbound", app="example-argocd-canary-linkerd"}[30s]))