apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generic-webapi
    role: backend
  name: {{ template "generic.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "generic.fullname" . }}
      role: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "generic.fullname" . }}
        role: backend
        date: "{{ date "20060102150405" now}}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
        {{- if .Values.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: back-event
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      restartPolicy: Always