apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generic-webapi
    role: backend
  name: {{ template "generic.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "generic.fullname" . }}
      role: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "generic.fullname" . }}
        role: backend
        date: "{{ date "20060102150405" now}}"
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
        {{ range $k, $v := .Values.extraEnvVars }}
          - name: "{{ $v.name }}"
            value: "{{ $v.value }}"
        {{- end }}
        envFrom:
          {{- if .Values.extraEnvVarsCM }}
          - configMapRef:
              name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsCM "context" $) }}
          {{- end }}
          {{- if .Values.extraEnvVarsSecret }}
          - secretRef:
              name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsSecret "context" $) }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: back-event
          protocol: TCP
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- if .Values.image.pullSecrets.useImageCredentials }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets.name }}
      {{- end }}